name: coastsnappy
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - opencv
  - numpy
  - matplotlib
  - pandas
  - scipy
  - poetry
  - tqdm
  - tensorflow 
  - typer
  - keras
  - scikit-image
  - openpyxl
  - spyder
  - imageai